processed 18 tasks

task 4 'run'. lines 25-33:
{
  "gas_used": 113964,
  "status": {
    "Keep": "Executed"
  }
}

task 5 'run'. lines 35-47:
{
  "gas_used": 132112,
  "status": {
    "Keep": "Executed"
  }
}

task 7 'run'. lines 51-64:
{
  "gas_used": 97685,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 68-81:
{
  "gas_used": 130304,
  "status": {
    "Keep": "Executed"
  }
}

task 11 'run'. lines 85-98:
{
  "gas_used": 91605,
  "status": {
    "Keep": "Executed"
  }
}

task 12 'run'. lines 100-113:
{
  "gas_used": 91605,
  "status": {
    "Keep": "Executed"
  }
}

task 14 'run'. lines 117-130:
{
  "gas_used": 143965,
  "status": {
    "Keep": "Executed"
  }
}

task 16 'run'. lines 134-147:
{
  "gas_used": 130304,
  "status": {
    "Keep": "Executed"
  }
}

task 17 'run'. lines 149-162:
{
  "gas_used": 32009,
  "status": {
    "Keep": {
      "MoveAbort": [
        "Script",
        1006
      ]
    }
  }
}
