name: 1. Build and Test
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: setup environment
        run: |
          sudo apt install curl -y
          curl -s https://raw.githubusercontent.com/starcoinorg/starcoin-framework/main/scripts/dev_setup.sh | bash /dev/stdin -b -t -y -p
      - name: build for starcoin
        working-directory: starcoin
        run: |
          source "$HOME/.profile"
          mpm package build
      - name: test for stracoin
        working-directory: starcoin
        run: |
          source "$HOME/.profile"
          mpm package test
      - name: integration test for starcoin
        working-directory: starcoin
        run: |
          source "$HOME/.profile"
          mpm integration-test
#      - name: move-prover-test
#        run: |
#          source "$HOME/.profile"
#          mpm package prove
